### ISSUE TITLE
UtilsApi.sql fails with `{"error":"query missing"}` but query works in mysql

### ISSUE THREAD

**Issue by narayanacharya6** [manticoresoftware/manticoresearch-python#8]
Example query fails when called via `UtilsApi.sql` in python client with`{"error":"query missing"}` but same query works in `mysql` client.

Steps to reproduce:

```
import manticoresearch
configuration = manticoresearch.Configuration(host="http://127.0.0.1:9308")
api_client = manticoresearch.ApiClient(configuration)
index_name = "test"
body = "CREATE TABLE {}(_id string, title text, content text, url string) ".format(index_name)
api_response = api_instance.sql(body, raw_response=True)
docs = [{"_id": "1", "title": "Test", "content": "Content", "metadata": {"url": "test.url"}}]
prepped_docs = [{
    "insert": {
        "index": index_name,
        "id": doc["_id"],
        "doc": {
            "_id": doc["_id"],
            "title": doc["title"],
            "content": doc["content"],
            "url": doc["metadata"]["url"]
        }
    }
} for doc in docs]
import json
api_instance = manticoresearch.IndexApi(api_client)
api_instance.bulk('\n'.join(map(json.dumps, prepped_docs)))
api_instance = manticoresearch.UtilsApi(api_client)
query = "example query"
max_k = 10
body = "SELECT *, WEIGHT(), PACKEDFACTORS({}) FROM {} WHERE MATCH('@(title,content){}') OPTION ranker=expr('sum(10000 * bm25f(1.2,0.75,{{title=1,content=1}}))'), idf='plain,tfidf_unnormalized', max_matches={}" \
                .format("{json=1}",
                        index_name,
                        '"{}"/1'.format(query.replace('\'', '')),
                        max_k)
api_instance.sql(body, raw_response=True)
```

Stack trace:
```
Traceback (most recent call last):
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/api/utils_api.py", line 68, in sql
    return self.sql_with_http_info(body, **kwargs)  # noqa: E501
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/api/utils_api.py", line 166, in sql_with_http_info
    return self.api_client.call_api(
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/api_client.py", line 373, in call_api
    return self.__call_api(resource_path, method,
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/api_client.py", line 189, in __call_api
    raise e
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/api_client.py", line 182, in __call_api
    response_data = self.request(
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/api_client.py", line 417, in request
    return self.rest_client.POST(url,
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/rest.py", line 263, in POST
    return self.request("POST", url,
  File "/Users/narayan/anaconda3/envs/ir-bm25-benchmark/lib/python3.10/site-packages/manticoresearch/rest.py", line 222, in request
    raise ApiException(http_resp=r)
manticoresearch.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Server': '4.2.1 3a946d53e@220330 release', 'Content-Type': 'application/json; charset=UTF-8', 'Content-Length': '25'})
HTTP response body: {"error":"query missing"}
```

When I run the same query via `mysql` directly in the docker container I get no errors:
```
mysql> SELECT *, WEIGHT(), PACKEDFACTORS({json=1}) FROM test WHERE MATCH('@(title,content)"example query"/1') OPTION ranker=expr('sum(10000 * bm25f(1.2,0.75,{title=1,content=1}))'), idf='plain,tfidf_unnormalized', max_matches=10;
mysql> 
```

Versions:
python client -> manticoresearch   1.0.6
server -> 4.2.1 3a946d53e@220330 release (running in docker container)

**Comment by githubmanticore** [comment]
➤ Nick Sergeev commented:
 

 
It appears, you use the Manticore dev version (4.2.1) that's not fully compatible with the current Python client release. 
The simplest way to fix the issue is to use the `raw_response=False` argument in your calls for SELECT queries, if the 'raw' response format is not a necessary thing for your app. 
Otherwise you've got to either use the Manticore stable version, or to build the client dev version from our repo [here](https://github.com/manticoresoftware/manticoresearch-python).
